In [ ]:
import torch

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[7.0387e-38, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.0216e-36]])


In [ ]:
x = torch.rand(5,3)
print(x)

tensor([[0.6056, 0.6231, 0.8146],
        [0.6464, 0.3346, 0.8092],
        [0.1655, 0.6862, 0.8288],
        [0.5957, 0.6959, 0.4083],
        [0.0624, 0.8210, 0.9526]])


In [ ]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.tensor([8.3,7])
print(x)

tensor([8.3000, 7.0000])


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.6038,  0.0873, -2.8064],
        [-0.2981,  0.3904, -0.9491],
        [ 0.6337,  0.5068, -0.8099],
        [-0.0834, -0.8213, -0.2911],
        [ 0.8932,  0.8627, -0.2089]])


In [ ]:
print(x.size())

torch.Size([5, 3])


In [ ]:
y = torch.rand(5,3)

In [ ]:
print(torch.add(x, y))

tensor([[ 1.4854,  0.7964, -2.2414],
        [ 0.5430,  1.1504, -0.2192],
        [ 1.2700,  0.5120, -0.4062],
        [ 0.1573, -0.2153, -0.0470],
        [ 0.9022,  1.5500,  0.4985]])


In [ ]:
#Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.4854,  0.7964, -2.2414],
        [ 0.5430,  1.1504, -0.2192],
        [ 1.2700,  0.5120, -0.4062],
        [ 0.1573, -0.2153, -0.0470],
        [ 0.9022,  1.5500,  0.4985]])


In [ ]:
# Addition: in-place
y.add_(x)
print(y)

tensor([[ 1.4854,  0.7964, -2.2414],
        [ 0.5430,  1.1504, -0.2192],
        [ 1.2700,  0.5120, -0.4062],
        [ 0.1573, -0.2153, -0.0470],
        [ 0.9022,  1.5500,  0.4985]])


In [ ]:
print(x[:,1])

tensor([ 0.0873,  0.3904,  0.5068, -0.8213,  0.8627])


In [ ]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
# Converting a Torch Tensor to a NumPy Array

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# Converting NumPy Array to Torch Tensor
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#Creating Tensor on GPU

if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5,3,device=device)
  y= torch.rand(5,3)
  y = y.to(device)
  z=x+y
  print(z)
  z =z.to("cpu")
  z.numpy()



tensor([[1.9463, 1.9703, 1.9910],
        [1.5083, 1.3066, 1.1388],
        [1.7732, 1.9666, 1.7378],
        [1.8356, 1.0721, 1.3505],
        [1.2361, 1.7187, 1.3256]], device='cuda:0')


In [ ]:
x= torch.rand(5,3,requires_grad=True)
print(x)

tensor([[0.1502, 0.3157, 0.7782],
        [0.1113, 0.3197, 0.9703],
        [0.1254, 0.0891, 0.2787],
        [0.1842, 0.3200, 0.0169],
        [0.0665, 0.9739, 0.6254]], requires_grad=True)
